// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DiamondBusinessObject.Models;

[Table("Bill")]
public partial class Bill
{
    [Key]
    public int BillId { get; set; }

    public int? CustomerId { get; set; }

    public int? PaymentId { get; set; }

    [InverseProperty("Bill")]
    public virtual ICollection<BillDiamond> BillDiamonds { get; set; } = new List<BillDiamond>();

    [InverseProperty("Bill")]
    public virtual ICollection<BillPromotion> BillPromotions { get; set; } = new List<BillPromotion>();

    [ForeignKey("CustomerId")]
    [InverseProperty("Bills")]
    public virtual Customer Customer { get; set; }
}