// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DiamondBusinessObject.Models;

[Table("Cart")]
public partial class Cart
{
    [Key]
    public int CartId { get; set; }

    public string UserId { get; set; }

    public int? DiamondId { get; set; }

    public int? JewelryId { get; set; }

    public int? Quantity { get; set; }

    public int? JewelrySizeId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateDate { get; set; }

    [ForeignKey("DiamondId")]
    [InverseProperty("Carts")]
    public virtual Diamond Diamond { get; set; }

    [ForeignKey("JewelryId")]
    [InverseProperty("Carts")]
    public virtual Jewelry Jewelry { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Carts")]
    public virtual User User { get; set; }


    [ForeignKey("JewelrySizeId")]
    [InverseProperty("Carts")]
    public virtual JewelrySize JewelrySize { get; set; }

    [InverseProperty("Cart")]
    public virtual ICollection<CartPromotion> CartPromotions { get; set; } = new List<CartPromotion>();

}