// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DiamondBusinessObject.Models;

[Table("DiamondPrice")]
public partial class DiamondPrice
{
    [Key]
    public int DiamondPriceId { get; set; }

    [StringLength(255)]
    public string Origin { get; set; }

    public double? CaratWeight { get; set; }

    [StringLength(255)]
    public string Color { get; set; }

    [StringLength(255)]
    public string Clarity { get; set; }

    [StringLength(255)]
    public string Cut { get; set; }

    public double? PricePerCarat { get; set; }

    public DateOnly? Date { get; set; }
}