// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DiamondBusinessObject.Models;

[Table("Diamond")]
public partial class Diamond
{
    [Key]
    public int DiamondId { get; set; }

    public int? DiamondTypeId { get; set; }

    public int? DiamondPriceId { get; set; }

    [StringLength(255)]
    public string Name { get; set; }

    [StringLength(255)]
    public string Barcode { get; set; }

    public bool? IsSold { get; set; }

    [StringLength(255)]
    public string Origin { get; set; }

    public double? CaratWeight { get; set; }

    [StringLength(255)]
    public string Color { get; set; }

    [StringLength(255)]
    public string Clarity { get; set; }

    [StringLength(255)]
    public string Cut { get; set; }

    [InverseProperty("Diamond")]
    public virtual ICollection<BillDiamond> BillDiamonds { get; set; } = new List<BillDiamond>();

    [InverseProperty("Diamond")]
    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    [InverseProperty("Diamond")]
    public virtual ICollection<DiamondMaterial> DiamondMaterials { get; set; } = new List<DiamondMaterial>();

    [ForeignKey("DiamondTypeId")]
    [InverseProperty("Diamonds")]
    public virtual DiamondType DiamondType { get; set; }

    [InverseProperty("Payment")]
    public virtual ICollection<OrderDiamond> OrderDiamonds { get; set; } = new List<OrderDiamond>();

    [InverseProperty("Diamond")]
    public virtual ICollection<Purchase> Purchases { get; set; } = new List<Purchase>();

    [InverseProperty("Diamond")]
    public virtual ICollection<Warranty> Warranties { get; set; } = new List<Warranty>();
}