// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DiamondBusinessObject.Models;

[Table("DiamondMaterial")]
public partial class DiamondMaterial
{
    [Key]
    public int DiamondMaterialId { get; set; }

    public int? MasterPriceId { get; set; }

    public int? DiamondId { get; set; }

    public int? MaterialId { get; set; }

    public double? Weight { get; set; }

    [ForeignKey("DiamondId")]
    [InverseProperty("DiamondMaterials")]
    public virtual Diamond Diamond { get; set; }

    [ForeignKey("MaterialId")]
    [InverseProperty("DiamondMaterials")]
    public virtual Material Material { get; set; }
}