// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DiamondBusinessObject.Models;

[Table("DiamondType")]
public partial class DiamondType
{
    [Key]
    public int DiamondTypeId { get; set; }

    [StringLength(255)]
    public string DiamondTypeName { get; set; }

    [InverseProperty("DiamondType")]
    public virtual ICollection<Diamond> Diamonds { get; set; } = new List<Diamond>();
}