// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DiamondBusinessObject.Models;

[Table("Material")]
public partial class Material
{
    [Key]
    public int MaterialId { get; set; }

    [StringLength(255)]
    public string Name { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [InverseProperty("Material")]
    public virtual ICollection<DiamondMaterial> DiamondMaterials { get; set; } = new List<DiamondMaterial>();
}