// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DiamondBusinessObject.Models;

[Table("OrderDiamond")]
public partial class OrderDiamond
{
    [Key]
    public int OrderDiamondId { get; set; }

    public int? PaymentId { get; set; }

    public int? DiamondId { get; set; }

    [ForeignKey("PaymentId")]
    [InverseProperty("OrderDiamonds")]
    public virtual Diamond Payment { get; set; }

    [ForeignKey("PaymentId")]
    [InverseProperty("OrderDiamonds")]
    public virtual Payment PaymentNavigation { get; set; }
}