// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DiamondBusinessObject.Models;

[Table("PaymentPromotion")]
public partial class PaymentPromotion
{
    [Key]
    public int PaymentPromotionId { get; set; }

    public int? PaymentId { get; set; }

    public int? PromotionId { get; set; }

    [ForeignKey("PaymentId")]
    [InverseProperty("PaymentPromotions")]
    public virtual Payment Payment { get; set; }

    [ForeignKey("PromotionId")]
    [InverseProperty("PaymentPromotions")]
    public virtual Promotion Promotion { get; set; }
}