// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DiamondBusinessObject.Models;

[Table("PaymentDiamond")]
public partial class PaymentDiamond
{
    [Key]
    public int PaymentDiamondId { get; set; }

    public int? PaymentId { get; set; }

    public int? DiamondId { get; set; }

    [ForeignKey("DiamondId")]
    [InverseProperty("PaymentDiamonds")]
    public virtual Diamond Diamond { get; set; }

    [ForeignKey("PaymentId")]
    [InverseProperty("PaymentDiamonds")]
    public virtual Payment Payment { get; set; }
}