// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DiamondBusinessObject.Models;

[Table("Promotion")]
public partial class Promotion
{
    [Key]
    public int PromotionId { get; set; }

    [StringLength(255)]
    public string PromotionType { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    public int PromotionCondition { get; set; }

    public double DiscountRate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    public bool Status { get; set; }

    [InverseProperty("Promotion")]
    public virtual ICollection<PaymentPromotion> PaymentPromotions { get; set; } = new List<PaymentPromotion>();

    [InverseProperty("Promotion")]
    public virtual ICollection<CartPromotion> CartPromotions { get; set; } = new List<CartPromotion>();

    [InverseProperty("Promotion")]
    public virtual ICollection<UserPromotion> UserPromotions { get; set; } = new List<UserPromotion>();
}