// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DiamondBusinessObject.Models;

[Table("Promotion")]
public partial class Promotion
{
    [Key]
    public int PromotionId { get; set; }

    [StringLength(255)]
    public string Type { get; set; }

    [StringLength(255)]
    public string ApproveManager { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    public double? DiscountRate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    [InverseProperty("Promotion")]
    public virtual ICollection<BillPromotion> BillPromotions { get; set; } = new List<BillPromotion>();
}