// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DiamondBusinessObject.Models;

[Table("Purchase")]
public partial class Purchase
{
    [Key]
    public int PurchaseId { get; set; }

    public int? CustomerId { get; set; }

    public int? UserId { get; set; }

    public int? DiamondId { get; set; }

    public DateOnly? PurchaseDate { get; set; }

    public double? PurchasePrice { get; set; }

    public bool? IsBuyBack { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Purchases")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("DiamondId")]
    [InverseProperty("Purchases")]
    public virtual Diamond Diamond { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Purchases")]
    public virtual User User { get; set; }
}