// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DiamondBusinessObject.Models;

[Table("Warranty")]
public partial class Warranty
{
    [Key]
    public int WarrantyId { get; set; }

    public int? DiamondId { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    public DateOnly? EndDate { get; set; }

    [ForeignKey("DiamondId")]
    [InverseProperty("Warranties")]
    public virtual Diamond Diamond { get; set; }
}