// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DiamondBusinessObject.Models;

public partial class DiamondStoreContext : DbContext
{
    public DiamondStoreContext()
    {
    }

    public DiamondStoreContext(DbContextOptions<DiamondStoreContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bill> Bills { get; set; }

    public virtual DbSet<BillDiamond> BillDiamonds { get; set; }

    public virtual DbSet<BillPromotion> BillPromotions { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Diamond> Diamonds { get; set; }

    public virtual DbSet<DiamondMaterial> DiamondMaterials { get; set; }

    public virtual DbSet<DiamondPrice> DiamondPrices { get; set; }

    public virtual DbSet<DiamondType> DiamondTypes { get; set; }

    public virtual DbSet<Material> Materials { get; set; }

    public virtual DbSet<OrderDiamond> OrderDiamonds { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<Promotion> Promotions { get; set; }

    public virtual DbSet<Purchase> Purchases { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Warranty> Warranties { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=THANGNGUYEN\\THANGNGUYEN;Initial Catalog=DiamondStore;Persist Security Info=True;User ID=sa;Password=Abcd1234");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bill>(entity =>
        {
            entity.HasKey(e => e.BillId).HasName("PK__Bill__11F2FC6A7BAB6967");

            entity.Property(e => e.BillId).ValueGeneratedNever();

            entity.HasOne(d => d.Customer).WithMany(p => p.Bills).HasConstraintName("FK__Bill__CustomerId__797309D9");
        });

        modelBuilder.Entity<BillDiamond>(entity =>
        {
            entity.HasKey(e => e.BillDiamondId).HasName("PK__BillDiam__82CC5E52BB3E8D0E");

            entity.Property(e => e.BillDiamondId).ValueGeneratedNever();

            entity.HasOne(d => d.Bill).WithMany(p => p.BillDiamonds).HasConstraintName("FK__BillDiamo__BillI__74AE54BC");

            entity.HasOne(d => d.Diamond).WithMany(p => p.BillDiamonds).HasConstraintName("FK__BillDiamo__Diamo__73BA3083");
        });

        modelBuilder.Entity<BillPromotion>(entity =>
        {
            entity.HasKey(e => e.BillPromotionId).HasName("PK__BillProm__470D21BE83C564BB");

            entity.Property(e => e.BillPromotionId).ValueGeneratedNever();

            entity.HasOne(d => d.Bill).WithMany(p => p.BillPromotions).HasConstraintName("FK__BillPromo__BillI__72C60C4A");

            entity.HasOne(d => d.Promotion).WithMany(p => p.BillPromotions).HasConstraintName("FK__BillPromo__Promo__71D1E811");
        });

        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasKey(e => e.CartId).HasName("PK__Cart__51BCD7B7AFE6B37F");

            entity.Property(e => e.CartId).ValueGeneratedNever();

            entity.HasOne(d => d.Customer).WithMany(p => p.Carts).HasConstraintName("FK__Cart__CustomerId__7A672E12");

            entity.HasOne(d => d.Diamond).WithMany(p => p.Carts).HasConstraintName("FK__Cart__DiamondId__7B5B524B");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PK__Customer__A4AE64D8E58F7A88");

            entity.Property(e => e.CustomerId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Diamond>(entity =>
        {
            entity.HasKey(e => e.DiamondId).HasName("PK__Diamond__23A8E79B1E258893");

            entity.Property(e => e.DiamondId).ValueGeneratedNever();

            entity.HasOne(d => d.DiamondType).WithMany(p => p.Diamonds).HasConstraintName("FK__Diamond__Diamond__70DDC3D8");
        });

        modelBuilder.Entity<DiamondMaterial>(entity =>
        {
            entity.HasKey(e => e.DiamondMaterialId).HasName("PK__DiamondM__65A6261382AB7A0B");

            entity.Property(e => e.DiamondMaterialId).ValueGeneratedNever();

            entity.HasOne(d => d.Diamond).WithMany(p => p.DiamondMaterials).HasConstraintName("FK__DiamondMa__Diamo__6EF57B66");

            entity.HasOne(d => d.Material).WithMany(p => p.DiamondMaterials).HasConstraintName("FK__DiamondMa__Mater__6E01572D");
        });

        modelBuilder.Entity<DiamondPrice>(entity =>
        {
            entity.HasKey(e => e.DiamondPriceId).HasName("PK__DiamondP__269074C7476FB6FC");

            entity.Property(e => e.DiamondPriceId).ValueGeneratedNever();
        });

        modelBuilder.Entity<DiamondType>(entity =>
        {
            entity.HasKey(e => e.DiamondTypeId).HasName("PK__DiamondT__2CC609EEB6BC46B1");

            entity.Property(e => e.DiamondTypeId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Material>(entity =>
        {
            entity.HasKey(e => e.MaterialId).HasName("PK__Material__C50610F7C644F01C");

            entity.Property(e => e.MaterialId).ValueGeneratedNever();
        });

        modelBuilder.Entity<OrderDiamond>(entity =>
        {
            entity.HasKey(e => e.OrderDiamondId).HasName("PK__OrderDia__26F55F1AAF96DF7E");

            entity.Property(e => e.OrderDiamondId).ValueGeneratedNever();

            entity.HasOne(d => d.Payment).WithMany(p => p.OrderDiamonds).HasConstraintName("FK__OrderDiam__Payme__6A30C649");

            entity.HasOne(d => d.PaymentNavigation).WithMany(p => p.OrderDiamonds).HasConstraintName("FK__OrderDiam__Payme__6B24EA82");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payment__9B556A38D70B917B");

            entity.Property(e => e.PaymentId).ValueGeneratedNever();

            entity.HasOne(d => d.Customer).WithMany(p => p.Payments).HasConstraintName("FK__Payment__Custome__6D0D32F4");
        });

        modelBuilder.Entity<PaymentMethod>(entity =>
        {
            entity.HasKey(e => e.PaymentMethodId).HasName("PK__PaymentM__DC31C1D3C51D2DF6");

            entity.Property(e => e.PaymentMethodId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Promotion>(entity =>
        {
            entity.HasKey(e => e.PromotionId).HasName("PK__Promotio__52C42FCF0235B5E4");

            entity.Property(e => e.PromotionId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Purchase>(entity =>
        {
            entity.HasKey(e => e.PurchaseId).HasName("PK__Purchase__6B0A6BBED0711ADA");

            entity.Property(e => e.PurchaseId).ValueGeneratedNever();

            entity.HasOne(d => d.Customer).WithMany(p => p.Purchases).HasConstraintName("FK__Purchase__Custom__778AC167");

            entity.HasOne(d => d.Diamond).WithMany(p => p.Purchases).HasConstraintName("FK__Purchase__Diamon__75A278F5");

            entity.HasOne(d => d.User).WithMany(p => p.Purchases).HasConstraintName("FK__Purchase__UserId__76969D2E");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__8AFACE1A1A0A0EA6");

            entity.Property(e => e.RoleId).ValueGeneratedNever();
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__1788CC4CAC3306C9");

            entity.Property(e => e.UserId).ValueGeneratedNever();

            entity.HasOne(d => d.Role).WithMany(p => p.Users).HasConstraintName("FK__User__RoleId__787EE5A0");
        });

        modelBuilder.Entity<Warranty>(entity =>
        {
            entity.HasKey(e => e.WarrantyId).HasName("PK__Warranty__2ED318135831C2B6");

            entity.Property(e => e.WarrantyId).ValueGeneratedNever();

            entity.HasOne(d => d.Diamond).WithMany(p => p.Warranties).HasConstraintName("FK__Warranty__Diamon__6FE99F9F");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}